### ISSUE TITLE
Mvp_simulation container can not find the path of myEnv

### ISSUE THREAD

**Issue by FelixDev0518** [openroboticmetaverse/mvp_mujoco_simulation#7]
## Expected Behavior
The mvp_simulation container should start its python virtual environment background automatically after the access into mvp_container. 

### Expected Procedure
```
$ docker exec -it mvp_simulation bash
Activating Local Env
(myEnv) root@docker-desktop:/sim_ws#
```

## Current Behavior
The mvp_simulation container can not find the path of myEnv/bin/activate
```
PS C:\...\open robotic metaverse\mvp_mujoco_simulation> docker exec -it mvp_simulation bash
Activating Local Env
: No such file or directory
root@docker-desktop:/sim_ws#
```
## Possible Solution
Optimizing the mvp_simulation container by introducing .env or entrypoint.sh instead of using env.sh

1.  Using .env
> In this way we should modify our Dockerfile as well.
> -  In .env
> ```
>...
># Absolute path of virtual environment foler
>virtual_env_path = /sim_ws/myEnv/bin/activate 
>...
>```
> - In Dockerfile
> ```
> ...
> RUN echo "source ${virtual_env_path}/start.sh" >> /root/.bashrc
> ...
> ```
2. Using entrypoint.sh
>In this way I suggest that we could run all processes of Dockerfile from the 10th line until 24th line in a file "entrypoint.sh". 
>ex)
> - Install all python background packages
> - Changing permission of files 
> - We can get rid of 14th line (COPY ./src ./src) and 15th line (COPY ./config ./config) in Dockerfile. Because we are using already bound mounting in docker-compose.yml 
> - In entrypoint.sh
>```
>WS_PATH='/sim_ws'
>mkdir -p $WS_PATH
>cd /sim_ws
>chmod +x start.sh
>
>/usr/bin/python3 -m venv myEnv
>$WS_PATH/myEnv/bin/python3 -m pip install -r requirements.txt
>```
> - In Dockerfile
>```
>...
>ENTRYPOINT ["bash", "entrypoint.sh"]
>...
>```
## Steps to Reproduce

1. Follow our test procedure "Set up" > "2. run container"

## Context (Environment)
OS: Windows 11
Docker version: Docker version 25.0.3, build 4debf41

**Comment by karimsiala** [comment]
On one hand I am questioning the utility of virtual environment inside a Docker container, since its already isolated right?
Do you think it makes sense to get rid of `venv` and install the packages directly inside the container?

On the other hand I say we keep it maybe in the future it might come in handy. What do you think? Should we keep it and go in the direction of using an `entrypoint.sh` script

**Comment by FelixDev0518** [comment]
In my opinion your second idea makes sense and is better solution because we use already virtual background with docker. But I am not sure that it will affects to some other points in container or any other background. I should test it. 

We can still use the process to building our container background. However, as I know it could be better to run like entrypoint.sh to build static background in container. We need to use and copy many containers later.
ps. is it better to assign other people?

**Comment by karimsiala** [comment]
@med-ayssar can you give us your input here since you added the virtual env so I think you have a better understanding of the issue.

In the meanwhile @FelixDev0518 I'd say just go with `entrypoint.sh`  give it a try and should be the working solution for now.
